/// <reference types="cypress" />

describe('Filtros_Devolucao', () => {
    it.only('Filtro_Devolucao_Todos', () => {
      cy.MAN_Acessar_Manager()
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]')
        .invoke('text')
        .then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_COD_DEVOLUCAO').type('4297')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[3]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('4.297')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_DEVOLUCAO').clear()
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#FLT_NUM_CGC').clear().type('91711840000118')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('Sem dados')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#FLT_NUM_CGC').clear().type('32387256883')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]/div')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_NUM_CGC').clear()
      cy.get('#FLT_DATA_CADASTRO').clear().type('03-05-2023')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[4]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('03-05-2023')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.contains('label', 'Somente Devolução com Nota emitida').click();
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.contains('label', 'Devolução Emitida para Loja Origem').click();
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[1]/div')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})

      //SELECT * FROM (SELECT * FROM TAB_TROCA TT WHERE COD_LOJA = 1 ORDER BY TT.DATA_ULTIMA_ALTERACAO DESC) WHERE ROWNUM <=3;
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[5]
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]/div	
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[2]/div	
      //COMPARAR VALORES - SELECT = 1° XPATH
      //COMPARAR VALORES - SELECT = 2° XPATH
      //COMPARAR VALORES - SELECT = 3° XPATH     
    })

    it('Filtro_Devolucao_Troca', () => {
      cy.MAN_Acessar_Manager()
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_COD_DEVOLUCAO').type('4307')
      cy.get('#FLT_DATA_CADASTRO').clear().type('03-05-2023')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[3]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('4.307')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_COD_DEVOLUCAO').clear()
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#FLT_NUM_CGC').clear().type('91711840000118')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('Sem dados')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#FLT_NUM_CGC').clear().type('32387256883')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]/div')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_DATA_CADASTRO').clear().type('03-05-2023')
      cy.get('#FLT_NUM_CGC').clear()
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[4]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('03-05-2023')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.contains('label', 'Somente Devolução com Nota emitida').click();
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]/div')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.contains('label', 'Devolução Emitida para Loja Origem').click();
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[2]/div')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('43')})

      //SELECT * FROM (SELECT * FROM TAB_TROCA TT WHERE COD_LOJA = 1 ORDER BY TT.DATA_ULTIMA_ALTERACAO DESC) WHERE ROWNUM <=3;
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[5]	
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]/div
      //OBTER VALOR = XPATH - /html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[2]/div	
      //COMPARAR VALORES - SELECT = 1° XPATH
      //COMPARAR VALORES - SELECT = 2° XPATH
      //COMPARAR VALORES - SELECT = 3° XPATH   

    })

    it('Filtro_Devolucao_Reembolso_com_Mov_Financeira', () => {
      cy.MAN_Acessar_Manager()
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('RCF')
      cy.get('#FLT_MOTIVO_REEMBOLSO').select('S')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#FLT_DATA_CADASTRO').clear().type('{enter}')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[1]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('RCF')
      cy.get('#FLT_MOTIVO_REEMBOLSO').select('S')
      cy.get('#FLT_COD_DEVOLUCAO').type('602')
      cy.get('#FLT_DATA_CADASTRO').clear().type('03-05-2023')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td[3]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('602')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('RCF')
      cy.get('#FLT_MOTIVO_REEMBOLSO').select('S')
      cy.get('#FLT_COD_DEVOLUCAO').clear()
      cy.get('#FLT_DATA_CADASTRO').clear().type('03-05-2023')
      cy.get('#FLT_NUM_CGC').clear().type('91711840000118')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr/td')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('Sem dados')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('RCF')
      cy.get('#FLT_MOTIVO_REEMBOLSO').select('S')
      cy.get('#FLT_DATA_CADASTRO').clear()
      cy.get('#FLT_NUM_CGC').clear().type('32387256883')
      cy.get('#EXEC_FILTRO_CUSTOM').click()
      cy.wait(2000)
      //cy.xpath('/html/body/div[1]/div[4]/section[7]/div/div[4]/div/div/div[2]/div/table/tbody/tr[1]/td[1]')
        //.invoke('text')
        //.then(text => {expect(text.trim()).to.equal('1')})
      cy.visit('http://10.245.0.12/manager/cad_devolucao.php5')
      cy.get('#FLT_COD_LOJA').select('1')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('TRO')
      cy.get('#FLT_FLG_TIPO_DEVOLUCAO').select('RCF')
      cy.get('#FLT_MOTIVO_REEMBOLSO').select('S')      



    })
      

})

